export enum PapelUsuario {
  ADMIN = 'ADMIN',
  FUNCIONARIO = 'FUNCIONARIO',
  FOTOGRAFO = 'FOTOGRAFO',
}

export enum StatusEnsaio {
  ORCAMENTO_ENVIADO = 'ORCAMENTO_ENVIADO',
  AGUARDANDO_RESPOSTA = 'AGUARDANDO_RESPOSTA',
  CONFIRMADO = 'CONFIRMADO',
  AGENDADO = 'AGENDADO',
  EM_ANDAMENTO = 'EM_ANDAMENTO',
  EDICAO = 'EDICAO',
  SELECAO_CLIENTE = 'SELECAO_CLIENTE',
  ENTREGUE = 'ENTREGUE',
  FINALIZADO = 'FINALIZADO',
  CANCELADO = 'CANCELADO',
}

export enum TipoTransacao {
  RECEITA = 'RECEITA',
  DESPESA = 'DESPESA',
}

export enum StatusTransacao {
  PENDENTE = 'PENDENTE',
  PAGO = 'PAGO',
  ATRASADO = 'ATRASADO',
  CANCELADO = 'CANCELADO',
}
