name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  security:
    uses: joaohenrique11z/teste_esteira/.github/workflows/pipeline.yml@v1
    with:
      project_name: 'Taella Photos'          # Nome usado no DefectDojo
      stack_type: 'node'                    # Opções: node, dotnet, python, java, cpp, go, rust
      run_dast: true                        # true = executa OWASP ZAP
      dast_target_url: 'https://taellaphotos.vercel.app'  # Obrigatório se run_dast: true
    secrets:
      DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
      DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}